import { NextRequest, NextResponse } from 'next/server';
import {
  GITHUB_DEFAULT_OWNER,
  GITHUB_DEFAULT_REPO,
  getGithubToken,
  webhookEventsLog,
} from '../../../../../src/lib/githubSync.ts';

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const {
    title,
    body: issueBodyInput,
    ticketId,
    deviceModel,
    telemetry,
    labels = ['bench-triage', 'hardware-diagnostic'],
  } = body || {};

  const owner = body?.owner || GITHUB_DEFAULT_OWNER;
  const repo = body?.repo || GITHUB_DEFAULT_REPO;
  const token = getGithubToken(req);

  if (!title) {
    return NextResponse.json({ error: 'Issue title is required' }, { status: 400 });
  }

  const issueTitle = ticketId ? `[Triage #${ticketId}] ${title}` : `[Bench Triage] ${title}`;

  let issueBody = issueBodyInput || '';
  if (telemetry || deviceModel) {
    issueBody += `\n\n### 🔬 Hardware Telemetry & Bench Record\n`;
    if (deviceModel) issueBody += `- **Device Model**: \`${deviceModel}\`\n`;
    if (ticketId) issueBody += `- **Ticket ID**: \`${ticketId}\`\n`;
    if (telemetry?.ammeterDrawAmps !== undefined) issueBody += `- **Ammeter Draw**: \`${telemetry.ammeterDrawAmps}A\`\n`;
    if (telemetry?.isShortToGround) issueBody += `- **Short to Ground**: ⚠️ **CONFIRMED SHORT**\n`;
    if (telemetry?.thermalHotspotCelsius) issueBody += `- **Thermal Hotspot**: \`${telemetry.thermalHotspotCelsius}°C\`\n`;
    issueBody += `\n*Automated triage issue generated by D&CP Spokane Lab Portal.*`;
  }

  try {
    if (token) {
      const ghRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Accept': 'application/vnd.github+json',
          'Content-Type': 'application/json',
          'User-Agent': 'DCP-Spokane-Lab-App',
        },
        body: JSON.stringify({
          title: issueTitle,
          body: issueBody,
          labels,
        }),
      });

      const issueData = (await ghRes.json()) as any;
      if (!ghRes.ok) {
        throw new Error(issueData.message || 'Failed to create GitHub Issue');
      }

      webhookEventsLog.unshift({
        id: `evt_issue_${Date.now()}`,
        event: 'issues',
        action: 'opened',
        deliveryId: `issue-${Date.now()}`,
        receivedAt: new Date().toISOString(),
        sender: {
          login: issueData.user?.login || 'cheyoung1983-sudo',
          avatar_url: issueData.user?.avatar_url,
        },
        repo: { name: repo, full_name: `${owner}/${repo}` },
        summary: `Created Issue #${issueData.number}: "${issueTitle.slice(0, 60)}"`,
        verified: true,
        payload: { issue: issueData },
      });

      return NextResponse.json({
        success: true,
        mode: 'live_github_api',
        issueNumber: issueData.number,
        htmlUrl: issueData.html_url,
        title: issueData.title,
        message: `Successfully opened Issue #${issueData.number} on GitHub`,
      });
    }

    // Local simulation mode
    const simNumber = Math.floor(Math.random() * 20) + 3;
    return NextResponse.json({
      success: true,
      mode: 'simulated_local',
      issueNumber: simNumber,
      htmlUrl: `https://github.com/${owner}/${repo}/issues/${simNumber}`,
      title: issueTitle,
      message: `Issue #${simNumber} generated. Sign in with GitHub OAuth to push directly to ${owner}/${repo}.`,
    });
  } catch (err: any) {
    console.error('GitHub Issue Creation Error:', err);
    return NextResponse.json({ error: err.message || 'Failed to open GitHub Issue' }, { status: 500 });
  }
}
