import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
  const clientEmail = (req.nextUrl.searchParams.get('email') || 'cheyoung1983@gmail.com').trim().toLowerCase();
  const clientName = (req.nextUrl.searchParams.get('name') || 'Che Young').trim();

  const orders = [
    {
      id: 'ord_dcp_8842',
      ticketNumber: 'DCP-8842',
      customerName: clientName,
      customerEmail: clientEmail,
      deviceManufacturer: 'Apple',
      deviceModel: 'iPhone 15 Pro Max',
      serviceTier: 'Tier 3 (Board Rework)',
      serviceCategory: 'Logic Board Micro-Soldering',
      status: 'in_progress',
      statusLabel: 'Parts Sourced & Staged',
      currentStage: 2,
      stageName: 'Parts Ordering & Sourcing',
      intakeDate: '2026-08-14T09:30:00Z',
      estimatedCompletionDate: 'Tomorrow at 3:15 PM',
      completedDate: null,
      deliveredDate: null,
      assignedTech: 'Marcus Vance (Senior Rework Specialist)',
      benchLocation: 'Spokane Bench Bin 104',
      issueDescription: 'Sudden reboot loop under high GPU load; thermal scan indicated VDD_MAIN short near U3100 PMIC.',
      serviceNotes: 'OEM PMIC component sourced from certified stock. Awaiting ultrasonic board prep prior to micro-soldering.',
      costs: {
        partsCost: 68.0,
        laborCost: 192.5,
        diagnosticFee: 35.0,
        expeditedFee: 0.0,
        subtotal: 295.5,
        waTaxRate: 0.091,
        taxAmount: 26.89,
        totalCost: 322.39,
        replacementSavingEstimate: 1199.0,
      },
      paymentStatus: 'paid',
      paymentMethod: 'Stripe Card (ending in 4242)',
      paymentDate: '2026-08-14T09:45:00Z',
      invoiceNumber: 'INV-2026-08842',
      warranty: {
        status: 'pending_completion',
        durationMonths: 12,
        coverageType: '1-Year Board & Component Guarantee',
        expiresDate: '2027-08-15',
        daysRemaining: 365,
      },
      telemetry: {
        batteryHealthPercentage: 88,
        batteryTempCelsius: 34,
        ammeterDrawAmps: 4.8,
        isShortToGround: true,
      },
    },
    {
      id: 'ord_dcp_9012',
      ticketNumber: 'DCP-9012',
      customerName: clientName,
      customerEmail: clientEmail,
      deviceManufacturer: 'Samsung',
      deviceModel: 'Galaxy S24 Ultra (512GB)',
      serviceTier: 'Tier 2 (Display Renewal)',
      serviceCategory: 'Dynamic AMOLED Assembly',
      status: 'in_progress',
      statusLabel: 'Bench Testing & Calibration',
      currentStage: 3,
      stageName: 'Bench Testing & Precision Rework',
      intakeDate: '2026-08-15T08:15:00Z',
      estimatedCompletionDate: 'Today at 5:30 PM',
      completedDate: null,
      deliveredDate: null,
      assignedTech: 'Elena Rostova (Optical & Display Lead)',
      benchLocation: 'Spokane Bench Bin 208',
      issueDescription: 'Digitizer ghost touch along lower quadrant following drop; glass shattered over front sensors.',
      serviceNotes: 'OEM Display Assembly installed. TrueTone and ultrasonic fingerprint sensor undergoing optical calibration.',
      costs: {
        partsCost: 185.0,
        laborCost: 95.0,
        diagnosticFee: 0.0,
        expeditedFee: 25.0,
        subtotal: 305.0,
        waTaxRate: 0.091,
        taxAmount: 27.76,
        totalCost: 332.76,
        replacementSavingEstimate: 1299.0,
      },
      paymentStatus: 'paid',
      paymentMethod: 'Shopify Draft Order Checkout',
      paymentDate: '2026-08-15T08:20:00Z',
      invoiceNumber: 'INV-2026-09012',
      warranty: {
        status: 'pending_completion',
        durationMonths: 12,
        coverageType: '1-Year OEM Display & Touch Grid Guarantee',
        expiresDate: '2027-08-15',
        daysRemaining: 365,
      },
      telemetry: {
        batteryHealthPercentage: 94,
        batteryTempCelsius: 31,
        ammeterDrawAmps: 0.85,
        isShortToGround: false,
      },
    },
    {
      id: 'ord_dcp_3109',
      ticketNumber: 'DCP-3109',
      customerName: clientName,
      customerEmail: clientEmail,
      deviceManufacturer: 'Apple',
      deviceModel: 'iPad Pro 12.9" (M2 Chip)',
      serviceTier: 'Tier 1 (Power/Port Refresh)',
      serviceCategory: 'USB-C Thunderbolt Power Delivery',
      status: 'completed',
      statusLabel: 'Delivered & Certified',
      currentStage: 4,
      stageName: 'Quality Assurance Stress Testing',
      intakeDate: '2026-07-22T10:00:00Z',
      estimatedCompletionDate: 'Completed',
      completedDate: '2026-07-23T16:45:00Z',
      deliveredDate: '2026-07-24T11:20:00Z',
      assignedTech: 'Marcus Vance',
      benchLocation: 'Spokane Bench Bin 302',
      issueDescription: 'Intermittent charging; USB-C cable wiggles loose and drops Power Delivery 30W negotiation.',
      serviceNotes: 'Replaced USB-C daughterboard assembly and re-flowed ESD protection diode array. Passed 45W thermal test.',
      costs: {
        partsCost: 45.0,
        laborCost: 55.0,
        diagnosticFee: 0.0,
        expeditedFee: 0.0,
        subtotal: 100.0,
        waTaxRate: 0.091,
        taxAmount: 9.1,
        totalCost: 109.1,
        replacementSavingEstimate: 1099.0,
      },
      paymentStatus: 'paid',
      paymentMethod: 'Stripe Card (ending in 4242)',
      paymentDate: '2026-07-22T10:15:00Z',
      invoiceNumber: 'INV-2026-03109',
      warranty: {
        status: 'active',
        durationMonths: 12,
        coverageType: '1-Year Port & Power Supply Guarantee',
        expiresDate: '2027-07-23',
        daysRemaining: 342,
      },
      telemetry: {
        batteryHealthPercentage: 91,
        batteryTempCelsius: 28,
        ammeterDrawAmps: 2.1,
        isShortToGround: false,
      },
    },
    {
      id: 'ord_dcp_7240',
      ticketNumber: 'DCP-7240',
      customerName: clientName,
      customerEmail: clientEmail,
      deviceManufacturer: 'Apple',
      deviceModel: 'MacBook Pro 16" (M1 Max / 32GB)',
      serviceTier: 'Tier 3 (Board Rework)',
      serviceCategory: 'Liquid Damage Ultrasonic Restoration',
      status: 'completed',
      statusLabel: 'Delivered & Certified',
      currentStage: 4,
      stageName: 'Quality Assurance Stress Testing',
      intakeDate: '2026-05-10T14:20:00Z',
      estimatedCompletionDate: 'Completed',
      completedDate: '2026-05-13T18:00:00Z',
      deliveredDate: '2026-05-14T09:30:00Z',
      assignedTech: 'Marcus Vance (Senior Rework Specialist)',
      benchLocation: 'Spokane Bench Bin 112',
      issueDescription: 'Spilled mineral water over keyboard. Unit refused to boot and was stuck in 5V 0.02A draw loop.',
      serviceNotes: 'Ultrasonic board clean, replaced corroded CD3217 USB-C controller chips and restored PPBUS_G3H 12.6V rail.',
      costs: {
        partsCost: 110.0,
        laborCost: 247.5,
        diagnosticFee: 45.0,
        expeditedFee: 50.0,
        subtotal: 452.5,
        waTaxRate: 0.091,
        taxAmount: 41.18,
        totalCost: 493.68,
        replacementSavingEstimate: 3199.0,
      },
      paymentStatus: 'paid',
      paymentMethod: 'Stripe Card (ending in 4242)',
      paymentDate: '2026-05-10T14:30:00Z',
      invoiceNumber: 'INV-2026-07240',
      warranty: {
        status: 'active',
        durationMonths: 12,
        coverageType: '1-Year Board & Liquid Decontamination Guarantee',
        expiresDate: '2027-05-13',
        daysRemaining: 271,
      },
      telemetry: {
        batteryHealthPercentage: 89,
        batteryTempCelsius: 32,
        ammeterDrawAmps: 3.25,
        isShortToGround: false,
      },
    },
    {
      id: 'ord_dcp_1845',
      ticketNumber: 'DCP-1845',
      customerName: clientName,
      customerEmail: clientEmail,
      deviceManufacturer: 'Apple',
      deviceModel: 'iPhone 13 Pro',
      serviceTier: 'Tier 1 (Power/Port Refresh)',
      serviceCategory: 'OEM High-Capacity Battery Renewal',
      status: 'completed',
      statusLabel: 'Delivered & Certified',
      currentStage: 4,
      stageName: 'Quality Assurance Stress Testing',
      intakeDate: '2026-01-18T11:45:00Z',
      estimatedCompletionDate: 'Completed',
      completedDate: '2026-01-18T16:15:00Z',
      deliveredDate: '2026-01-19T10:00:00Z',
      assignedTech: 'Elena Rostova',
      benchLocation: 'Spokane Bench Bin 105',
      issueDescription: 'Battery health degraded to 72% with sudden shutdown at 20% charge.',
      serviceNotes: 'Installed new OEM-grade cell with serialized BMS calibration. 100% capacity verified over 3 thermal cycles.',
      costs: {
        partsCost: 45.0,
        laborCost: 45.0,
        diagnosticFee: 0.0,
        expeditedFee: 0.0,
        subtotal: 90.0,
        waTaxRate: 0.091,
        taxAmount: 8.19,
        totalCost: 98.19,
        replacementSavingEstimate: 699.0,
      },
      paymentStatus: 'paid',
      paymentMethod: 'Shopify POS Card Payment',
      paymentDate: '2026-01-18T12:00:00Z',
      invoiceNumber: 'INV-2026-01845',
      warranty: {
        status: 'active',
        durationMonths: 12,
        coverageType: '1-Year Battery Capacity Retention Guarantee',
        expiresDate: '2027-01-18',
        daysRemaining: 156,
      },
      telemetry: {
        batteryHealthPercentage: 100,
        batteryTempCelsius: 27,
        ammeterDrawAmps: 1.85,
        isShortToGround: false,
      },
    },
  ];

  // Compute aggregate summary metrics
  const totalRepairCosts = orders.reduce((acc, o) => acc + o.costs.totalCost, 0);
  const activeOrders = orders.filter((o) => o.status === 'in_progress');
  const completedOrders = orders.filter((o) => o.status === 'completed');
  const activeRepairCosts = activeOrders.reduce((acc, o) => acc + o.costs.totalCost, 0);
  const completedRepairCosts = completedOrders.reduce((acc, o) => acc + o.costs.totalCost, 0);
  const totalPartsCosts = orders.reduce((acc, o) => acc + o.costs.partsCost, 0);
  const totalLaborCosts = orders.reduce((acc, o) => acc + o.costs.laborCost, 0);
  const totalReplacementSavings = orders.reduce((acc, o) => acc + o.costs.replacementSavingEstimate, 0);
  const activeWarranties = orders.filter((o) => o.warranty.status === 'active').length;

  return NextResponse.json({
    success: true,
    client: {
      name: clientName,
      email: clientEmail,
      phone: '(509) 555-0194',
      location: 'Spokane, WA (99201)',
      memberSince: 'October 2025',
      accountTier: 'Premier Priority Fleet',
      accountBadge: 'Verified Lab Client',
      totalOrdersCount: orders.length,
      activeOrdersCount: activeOrders.length,
      completedOrdersCount: completedOrders.length,
    },
    summary: {
      totalRepairCosts: Number(totalRepairCosts.toFixed(2)),
      activeRepairCosts: Number(activeRepairCosts.toFixed(2)),
      completedRepairCosts: Number(completedRepairCosts.toFixed(2)),
      totalPartsCosts: Number(totalPartsCosts.toFixed(2)),
      totalLaborCosts: Number(totalLaborCosts.toFixed(2)),
      totalReplacementSavings: Number(totalReplacementSavings.toFixed(2)),
      netValueRetained: Number((totalReplacementSavings - totalRepairCosts).toFixed(2)),
      averageRepairCost: Number((totalRepairCosts / orders.length).toFixed(2)),
      activeWarrantiesCount: activeWarranties,
      totalOrdersCount: orders.length,
      activeCount: activeOrders.length,
      completedCount: completedOrders.length,
    },
    orders,
  });
}
