import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Sparkles,
  Wrench,
  AlertTriangle,
  Clock,
  CheckCircle2,
  Circle,
  Copy,
  RotateCw,
  Cpu,
  ShieldAlert,
  ListOrdered,
  ArrowRight,
  Layers,
  ChevronDown,
  ChevronUp,
  SlidersHorizontal,
  Bot
} from 'lucide-react';
import { useToast } from './Toast.tsx';
import { TelemetryData } from '../types.ts';

export interface DiagnosticStep {
  stepNumber: number;
  actionTitle: string;
  instructions: string;
  expectedReading: string;
  toolRequired: string;
}

export interface RecommendedDiagnosticPathData {
  primaryDiagnosis: string;
  confidenceScore: number;
  complexityLevel: string;
  estimatedBenchTimeMinutes: number;
  technicianBriefing: string;
  diagnosticSteps: DiagnosticStep[];
  requiredTools: string[];
  riskPrecautions: string[];
  partsLikelyNeeded: string[];
}

interface RecommendedDiagnosticPathProps {
  repairNotes: string;
  deviceManufacturer: string;
  deviceModel: string;
  symptoms?: string[];
  telemetry?: TelemetryData;
  onApplyPathToNotes?: (formattedPath: string) => void;
}

export default function RecommendedDiagnosticPath({
  repairNotes,
  deviceManufacturer,
  deviceModel,
  symptoms = [],
  telemetry,
  onApplyPathToNotes
}: RecommendedDiagnosticPathProps) {
  const { showToast } = useToast();
  const [loading, setLoading] = useState(false);
  const [pathData, setPathData] = useState<RecommendedDiagnosticPathData | null>(null);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [expandedStep, setExpandedStep] = useState<number | null>(1);
  const [autoGeneratedForNotes, setAutoGeneratedForNotes] = useState<string>('');

  const generateDiagnosticPath = async () => {
    if (!repairNotes.trim() && symptoms.length === 0) {
      showToast('Please enter repair notes or select symptoms to generate a diagnostic path.', 'error');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch('/api/ai/diagnostic-path', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repairNotes,
          deviceManufacturer,
          deviceModel,
          symptoms,
          telemetry
        })
      });

      const contentType = response.headers.get('content-type') || '';
      if (!contentType.includes('application/json')) {
        throw new Error(`Server returned non-JSON response (${response.status})`);
      }

      const res = await response.json();
      if (response.ok && res.success && res.path) {
        setPathData(res.path);
        setCompletedSteps([]);
        setExpandedStep(1);
        setAutoGeneratedForNotes(repairNotes);
        showToast('OpenAI Recommended Diagnostic Path generated!', 'success');
      } else {
        showToast(res.error || 'Failed to generate diagnostic path.', 'error');
      }
    } catch (err) {
      console.error('Error generating diagnostic path:', err);
      showToast('Connection error. Could not generate diagnostic path.', 'error');
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate if notes exist and no path has been generated yet
  useEffect(() => {
    if (
      repairNotes.trim().length > 10 &&
      !pathData &&
      !loading &&
      autoGeneratedForNotes !== repairNotes
    ) {
      // Auto trigger with slight delay to avoid rapid re-fetching while typing
      const timer = setTimeout(() => {
        generateDiagnosticPath();
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [repairNotes, deviceModel, symptoms]);

  const toggleStepCompleted = (stepNum: number) => {
    setCompletedSteps(prev =>
      prev.includes(stepNum) ? prev.filter(s => s !== stepNum) : [...prev, stepNum]
    );
  };

  const handleApplyToNotes = () => {
    if (!pathData) return;

    const formatted = `
=== OPENAI RECOMMENDED DIAGNOSTIC PATH ===
Primary Diagnosis: ${pathData.primaryDiagnosis} (${pathData.confidenceScore}% Confidence)
Complexity: ${pathData.complexityLevel} | Est. Bench Time: ${pathData.estimatedBenchTimeMinutes} mins

TECHNICIAN BRIEFING:
${pathData.technicianBriefing}

RECOMMENDED BENCH EXECUTION STEPS:
${pathData.diagnosticSteps.map(s => `${s.stepNumber}. [${s.actionTitle}] ${s.instructions} (Expected: ${s.expectedReading} | Tool: ${s.toolRequired})`).join('\n')}

REQUIRED BENCH TOOLS: ${pathData.requiredTools.join(', ')}
PARTS LIKELY NEEDED: ${pathData.partsLikelyNeeded.join(', ')}
SAFETY PRECAUTIONS: ${pathData.riskPrecautions.join('; ')}
`.trim();

    if (onApplyPathToNotes) {
      onApplyPathToNotes(formatted);
    } else {
      navigator.clipboard.writeText(formatted);
      showToast('Diagnostic Path copied to clipboard!', 'success');
    }
  };

  return (
    <div className="bg-slate-900 text-white rounded-3xl p-6 md:p-8 space-y-6 shadow-2xl border border-slate-800 relative overflow-hidden">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 flex items-center justify-center shrink-0 shadow-lg shadow-blue-500/20">
            <Sparkles className="w-6 h-6 text-white animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-xl font-bold text-white tracking-tight">Recommended Diagnostic Path</h3>
              <span className="px-2.5 py-0.5 bg-blue-500/20 text-blue-400 text-[10px] font-mono font-bold rounded-full border border-blue-500/30">
                OPENAI GPT-4o
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              AI-driven technical roadmap based on repair notes, symptoms, and hardware telemetry
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={generateDiagnosticPath}
          disabled={loading}
          className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white text-xs font-bold rounded-xl transition-all shadow-lg shadow-blue-600/30 flex items-center justify-center gap-2 disabled:opacity-50 self-start sm:self-auto"
        >
          {loading ? (
            <>
              <RotateCw className="w-4 h-4 animate-spin" />
              <span>Analyzing Notes...</span>
            </>
          ) : (
            <>
              <Bot className="w-4 h-4" />
              <span>{pathData ? 'Re-Analyze Path' : 'Generate Diagnostic Path'}</span>
            </>
          )}
        </button>
      </div>

      {/* Main Content Area */}
      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="py-12 flex flex-col items-center justify-center text-center space-y-4"
          >
            <div className="relative">
              <div className="w-16 h-16 rounded-2xl bg-blue-600/20 border border-blue-500/30 flex items-center justify-center animate-bounce">
                <Cpu className="w-8 h-8 text-blue-400" />
              </div>
              <div className="absolute -top-1 -right-1 w-4 h-4 bg-emerald-500 rounded-full animate-ping" />
            </div>
            <div className="space-y-1">
              <p className="text-sm font-bold text-slate-200">Synthesizing Diagnostic Execution Plan...</p>
              <p className="text-xs text-slate-400">Evaluating repair notes against D&CP Lab schematics & power rail specs</p>
            </div>
          </motion.div>
        ) : pathData ? (
          <motion.div
            key="result"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="space-y-6"
          >
            {/* Summary Header Badge Grid */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="md:col-span-2 bg-slate-800/80 border border-slate-700/80 rounded-2xl p-4 space-y-2">
                <span className="text-[10px] font-bold uppercase tracking-wider text-blue-400 flex items-center gap-1.5">
                  <Cpu className="w-3.5 h-3.5" />
                  Primary Suspected Fault
                </span>
                <p className="text-base font-bold text-white">{pathData.primaryDiagnosis}</p>
                <div className="flex items-center gap-2 pt-1">
                  <div className="w-full bg-slate-700 h-1.5 rounded-full overflow-hidden">
                    <div
                      className="bg-emerald-400 h-full rounded-full transition-all duration-500"
                      style={{ width: `${pathData.confidenceScore}%` }}
                    />
                  </div>
                  <span className="text-[10px] font-mono font-bold text-emerald-400 shrink-0">
                    {pathData.confidenceScore}% Confidence
                  </span>
                </div>
              </div>

              <div className="bg-slate-800/80 border border-slate-700/80 rounded-2xl p-4 flex flex-col justify-between">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Layers className="w-3.5 h-3.5 text-amber-400" />
                  Service Complexity
                </span>
                <p className="text-sm font-bold text-amber-300 mt-1">{pathData.complexityLevel}</p>
                <span className="text-[10px] text-slate-400 mt-2">D&CP Standard Classification</span>
              </div>

              <div className="bg-slate-800/80 border border-slate-700/80 rounded-2xl p-4 flex flex-col justify-between">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Clock className="w-3.5 h-3.5 text-indigo-400" />
                  Est. Bench Time
                </span>
                <p className="text-sm font-bold text-indigo-300 mt-1">{pathData.estimatedBenchTimeMinutes} Minutes</p>
                <span className="text-[10px] text-slate-400 mt-2">Isolation & Testing</span>
              </div>
            </div>

            {/* Technician Briefing Box */}
            <div className="bg-blue-950/40 border border-blue-500/30 rounded-2xl p-4 md:p-5 space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-300 flex items-center gap-2">
                <Bot className="w-4 h-4 text-blue-400" />
                Technician Triage Briefing
              </h4>
              <p className="text-xs text-slate-300 leading-relaxed font-medium">
                {pathData.technicianBriefing}
              </p>
            </div>

            {/* Step-By-Step Diagnostic Execution Steps */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                  <ListOrdered className="w-4 h-4 text-blue-400" />
                  Sequential Diagnostic Steps ({completedSteps.length}/{pathData.diagnosticSteps.length} Complete)
                </h4>
                {completedSteps.length === pathData.diagnosticSteps.length && (
                  <span className="text-[10px] font-bold text-emerald-400 bg-emerald-500/20 px-2 py-0.5 rounded-full border border-emerald-500/30 flex items-center gap-1">
                    <CheckCircle2 className="w-3 h-3" /> All Steps Verified
                  </span>
                )}
              </div>

              <div className="space-y-2">
                {pathData.diagnosticSteps.map((step) => {
                  const isDone = completedSteps.includes(step.stepNumber);
                  const isExpanded = expandedStep === step.stepNumber;

                  return (
                    <div
                      key={step.stepNumber}
                      className={`border rounded-2xl transition-all overflow-hidden ${
                        isDone
                          ? 'bg-slate-800/40 border-emerald-500/30'
                          : isExpanded
                          ? 'bg-slate-800 border-blue-500/50 shadow-lg'
                          : 'bg-slate-800/70 border-slate-700/80 hover:border-slate-600'
                      }`}
                    >
                      {/* Step Header Line */}
                      <div className="p-4 flex items-center justify-between gap-3 cursor-pointer select-none" onClick={() => setExpandedStep(isExpanded ? null : step.stepNumber)}>
                        <div className="flex items-center gap-3 min-w-0">
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation();
                              toggleStepCompleted(step.stepNumber);
                            }}
                            className="p-1 text-slate-400 hover:text-white transition-colors shrink-0"
                          >
                            {isDone ? (
                              <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                            ) : (
                              <Circle className="w-5 h-5 text-slate-500" />
                            )}
                          </button>

                          <div className="min-w-0">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="text-xs font-mono font-bold text-blue-400">
                                STEP {step.stepNumber}
                              </span>
                              <h5 className={`text-sm font-bold truncate ${isDone ? 'line-through text-slate-400' : 'text-white'}`}>
                                {step.actionTitle}
                              </h5>
                            </div>
                          </div>
                        </div>

                        <div className="flex items-center gap-2 shrink-0">
                          <span className="text-[10px] bg-slate-900/80 text-slate-300 px-2 py-1 rounded-lg border border-slate-700/60 font-mono hidden sm:inline-block">
                            {step.toolRequired}
                          </span>
                          {isExpanded ? (
                            <ChevronUp className="w-4 h-4 text-slate-400" />
                          ) : (
                            <ChevronDown className="w-4 h-4 text-slate-400" />
                          )}
                        </div>
                      </div>

                      {/* Step Detailed Drawer */}
                      {isExpanded && (
                        <div className="px-4 pb-4 pt-1 border-t border-slate-700/60 space-y-3 bg-slate-900/40">
                          <p className="text-xs text-slate-300 leading-relaxed">
                            {step.instructions}
                          </p>

                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1 text-xs">
                            <div className="p-2.5 rounded-xl bg-slate-800/90 border border-slate-700/60">
                              <span className="text-[10px] font-bold text-slate-400 block uppercase tracking-wider">
                                Expected Nominal Reading
                              </span>
                              <span className="font-mono font-bold text-emerald-300">
                                {step.expectedReading}
                              </span>
                            </div>

                            <div className="p-2.5 rounded-xl bg-slate-800/90 border border-slate-700/60">
                              <span className="text-[10px] font-bold text-slate-400 block uppercase tracking-wider">
                                Required Instrument / Tool
                              </span>
                              <span className="font-bold text-blue-300">
                                {step.toolRequired}
                              </span>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Tools, Parts & Precautions Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
              {/* Tools */}
              <div className="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-4 space-y-2">
                <span className="text-xs font-bold text-blue-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Wrench className="w-3.5 h-3.5" />
                  Required Bench Tools
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {pathData.requiredTools.map((tool, idx) => (
                    <span key={idx} className="px-2 py-1 bg-slate-900 text-slate-300 text-[11px] font-medium rounded-lg border border-slate-700/80">
                      {tool}
                    </span>
                  ))}
                </div>
              </div>

              {/* Likely Parts */}
              <div className="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-4 space-y-2">
                <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center gap-1.5">
                  <SlidersHorizontal className="w-3.5 h-3.5" />
                  Likely Needed Parts
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {pathData.partsLikelyNeeded.map((part, idx) => (
                    <span key={idx} className="px-2 py-1 bg-slate-900 text-slate-300 text-[11px] font-medium rounded-lg border border-slate-700/80">
                      {part}
                    </span>
                  ))}
                </div>
              </div>

              {/* Safety Precautions */}
              <div className="bg-amber-950/30 border border-amber-500/30 rounded-2xl p-4 space-y-2">
                <span className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                  <ShieldAlert className="w-3.5 h-3.5 text-amber-400" />
                  Hazard & Risk Precautions
                </span>
                <ul className="space-y-1 text-xs text-amber-200/90 list-disc list-inside">
                  {pathData.riskPrecautions.map((risk, idx) => (
                    <li key={idx} className="leading-snug">
                      {risk}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Bottom Actions */}
            <div className="pt-2 flex flex-col sm:flex-row items-center justify-between gap-3 border-t border-slate-800">
              <p className="text-[11px] text-slate-400">
                Path generated for Spokane Lab work orders. Results align with ESD & IPC-A-610 standards.
              </p>

              <button
                type="button"
                onClick={handleApplyToNotes}
                className="w-full sm:w-auto px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl transition-all shadow-md flex items-center justify-center gap-2"
              >
                <Copy className="w-4 h-4" />
                <span>Apply Path to Work Order Notes</span>
              </button>
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="empty"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="py-10 text-center space-y-4 border-2 border-dashed border-slate-800 rounded-2xl p-6"
          >
            <div className="w-12 h-12 bg-slate-800 text-slate-400 rounded-2xl flex items-center justify-center mx-auto">
              <Bot className="w-6 h-6" />
            </div>
            <div className="max-w-md mx-auto space-y-1">
              <h4 className="text-sm font-bold text-white">No Diagnostic Path Generated Yet</h4>
              <p className="text-xs text-slate-400">
                Enter repair notes or symptom details above, then click <strong className="text-slate-200">Generate Diagnostic Path</strong> to generate step-by-step bench instructions.
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
