#!/usr/bin/env node
/**
 * Preflight — run the CI gate locally, the way CI actually runs it.
 *
 * This exists because of a specific failure mode: `tsconfig.json` includes
 * `next-env.d.ts` and `.next/types/**`, both of which are generated by
 * `next dev` / `next build` and both of which are gitignored. Anyone who has
 * run the dev server has them on disk, so `npm run lint` passes locally — but
 * CI checks out a bare tree and runs `lint` BEFORE `build`, so those files do
 * not exist yet and the typecheck fails on things like static image imports.
 *
 * So this script deletes the generated type artifacts first, reproducing a
 * fresh checkout, then runs lint -> test -> build in CI order. A local pass
 * therefore means something.
 *
 * It does not, and cannot, guarantee CI succeeds — CI runs on a different
 * Node version matrix and a clean dependency install. What it guarantees is
 * that you find this class of failure before pushing rather than after.
 *
 * Usage:
 *   node scripts/preflight.mjs           # lint -> test -> build
 *   node scripts/preflight.mjs --quick   # lint -> test (skip the slow build)
 *   node scripts/preflight.mjs --keep    # don't clear generated types first
 */
import { spawnSync } from 'node:child_process';
import { rmSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const args = new Set(process.argv.slice(2));
const quick = args.has('--quick');
const keep = args.has('--keep');

const useColor = process.stdout.isTTY && !process.env.NO_COLOR;
const paint = (code) => (useColor ? `\u001b[${code}m` : '');
const C = {
  reset: paint(0),
  dim: paint(2),
  red: paint(31),
  green: paint(32),
  yellow: paint(33),
  bold: paint(1),
};

function log(msg = '') {
  process.stdout.write(`${msg}\n`);
}

function heading(msg) {
  log(`\n${C.bold}${msg}${C.reset}`);
}

// Generated type artifacts that mask the CI failure when present locally.
const GENERATED = ['next-env.d.ts', '.next/types', 'tsconfig.tsbuildinfo'];

function clearGeneratedTypes() {
  const cleared = [];
  for (const rel of GENERATED) {
    const abs = join(root, rel);
    if (existsSync(abs)) {
      rmSync(abs, { recursive: true, force: true });
      cleared.push(rel);
    }
  }
  return cleared;
}

function run(label, command, commandArgs) {
  heading(`▶ ${label}`);
  log(`${C.dim}$ ${command} ${commandArgs.join(' ')}${C.reset}`);
  const started = Date.now();
  const result = spawnSync(command, commandArgs, {
    stdio: 'inherit',
    shell: process.platform === 'win32',
    cwd: root,
  });
  const secs = ((Date.now() - started) / 1000).toFixed(1);

  if (result.status === 0) {
    log(`${C.green}✓ ${label} passed${C.reset} ${C.dim}(${secs}s)${C.reset}`);
    return true;
  }
  log(`${C.red}✗ ${label} failed${C.reset} ${C.dim}(${secs}s)${C.reset}`);
  return false;
}

function checkNodeVersion() {
  const major = Number(process.versions.node.split('.')[0]);
  let ciVersions = [];
  const workflow = join(root, '.github/workflows/ci.yml');
  if (existsSync(workflow)) {
    const text = readFileSync(workflow, 'utf8');
    const match = text.match(/node-version:\s*\[([^\]]+)\]/);
    if (match) {
      ciVersions = match[1]
        .split(',')
        .map((v) => Number(v.trim().replace(/['"]/g, '').split('.')[0]))
        .filter((n) => !Number.isNaN(n));
    }
  }
  if (ciVersions.length > 0 && !ciVersions.includes(major)) {
    log(
      `${C.yellow}! Local Node is ${major}.x; CI builds on ${ciVersions
        .map((v) => `${v}.x`)
        .join(', ')}. A pass here does not cover those.${C.reset}`
    );
  }
}

heading('Preflight — reproducing the CI gate');
checkNodeVersion();

if (!existsSync(join(root, 'node_modules'))) {
  log(`${C.red}✗ node_modules is missing. Run: npm install${C.reset}`);
  process.exit(1);
}

if (keep) {
  log(`${C.yellow}! --keep: leaving generated types in place. This can hide a CI-only failure.${C.reset}`);
} else {
  const cleared = clearGeneratedTypes();
  log(
    cleared.length > 0
      ? `${C.dim}Cleared generated types so the typecheck matches a fresh checkout: ${cleared.join(', ')}${C.reset}`
      : `${C.dim}No generated type artifacts present — already matches a fresh checkout.${C.reset}`
  );
}

const steps = [
  ['Lint & Typecheck', 'npm', ['run', 'lint']],
  ['Unit Tests', 'npm', ['run', 'test']],
];
if (!quick) steps.push(['Build', 'npm', ['run', 'build']]);

for (const [label, cmd, cmdArgs] of steps) {
  if (run(label, cmd, cmdArgs)) continue;

  log(`\n${C.red}${C.bold}Preflight failed at: ${label}${C.reset}`);
  if (label === 'Lint & Typecheck') {
    log(
      `\n${C.dim}If the errors are "Cannot find module" on .jpg/.png/.svg imports,\n` +
        `the tracked declaration at types/next-images.d.ts is missing or was\n` +
        `deleted. Those types come from the gitignored next-env.d.ts, which does\n` +
        `not exist yet when CI runs lint before build.${C.reset}`
    );
  }
  log(`\n${C.dim}Fix the errors above and re-run. Do not skip the step to get green.${C.reset}`);
  process.exit(1);
}

log(`\n${C.green}${C.bold}✓ Preflight passed${C.reset}`);
log(
  `${C.dim}lint, tests${quick ? '' : ', and build'} all pass from a clean-types state.${C.reset}`
);
if (quick) {
  log(`${C.yellow}! --quick skipped the build. Run without --quick before pushing.${C.reset}`);
}
